### ISSUE TITLE
Switch to multi-arch build and images

### ISSUE THREAD

**Issue by mahnunchik** [home-assistant/builder#223]
It's been two years since the last discussion of this topic https://github.com/home-assistant/builder/issues/131

All the software I use has switched to multi-architecture images in docker world. The technology has become stable over the past two years.

Maybe it makes sense to switch to a multi-arc build and multi-arch images. This will greatly simplify the build step of add-ons and save "kilometers" of documentation.

### From

| Image | OS | Tags | latest |
|-------|----|------|--------|
| armhf-base | Alpine | 3.17 3.18, 3.19, 3.20 | 3.20 |
| armv7-base | Alpine | 3.17 3.18, 3.19, 3.20 | 3.20 |
| aarch64-base | Alpine | 3.17 3.18, 3.19, 3.20 | 3.20 |
| amd64-base | Alpine | 3.17 3.18, 3.19, 3.20 | 3.20 |
| i386-base | Alpine | 3.17 3.18, 3.19, 3.20 | 3.20 |

### To

| Image | OS | Tags | latest |
|-------|----|------|--------|
| base | Alpine | 3.17 3.18, 3.19, 3.20 | 3.20 |

---
https://github.com/home-assistant/core/blob/dev/build.yaml#L1-L7

### From

```yml
image: ghcr.io/home-assistant/{arch}-homeassistant
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-homeassistant-base:2024.06.1
  armhf: ghcr.io/home-assistant/armhf-homeassistant-base:2024.06.1
  armv7: ghcr.io/home-assistant/armv7-homeassistant-base:2024.06.1
  amd64: ghcr.io/home-assistant/amd64-homeassistant-base:2024.06.1
  i386: ghcr.io/home-assistant/i386-homeassistant-base:2024.06.1
```

### To

```yml
image: ghcr.io/home-assistant/homeassistant
build_from: ghcr.io/home-assistant/homeassistant-base:2024.06.1
```

Or even
```yml
image: ghcr.io/home-assistant/homeassistant
```
Together with
```Dockerfile
FROM: ghcr.io/home-assistant/homeassistant-base:2024.06.1
```
---

It seems hassio has been already switched https://github.com/hassio-addons/addon-base/pkgs/container/base
